---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: dev-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: secdevopsjourney/nginx:v0.3.0
        ports:
        - containerPort: 80
